### PR TITLE
feature:Add HTML UI

### PR DESCRIPTION
**Pull request by newspring0203**
HTML - BOB 입니다.

### CODE REVIEW

**Comment by june0216** [comment]
두 번째 숫자를 넣는 <input> 태그가 누락되었습니다.
 다시 반영해주세요

**Comment by june0216** [comment]
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Calculator</title>
    <link rel="stylesheet" href="style.css">
    <script defer src="app.js"></script>
</head>

<body>
    <form id="form">
        <input type="text" id="first" class="question" />
        <label for="first"><span>첫 번째 숫자</span></label>        
        <input type="text" id="second" class="question" />
        <label for="second"><span>두 번째 숫자</span></label>
        <input type="submit" value="계산" />
    </form>
    <div id="output"></div>
</body>

</html>

**Comment by newspring0203** [comment]
다시 추가했습니다!

**Comment by june0216** [comment]
확인했습니다.

**Pull request merged**
